# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Joy.ApplicationSecurity-VSTS.custom-build-release-task.HCLAppScan@1
  inputs:
    AppSecTestService: 'Rohan_ASOC_Prod'
    applications: '9b6878b0-fd8a-451b-ad75-23860e5e29c3'
    scanname: 'Y4'
    scantype: 'static'

- task: HCL AppScan Enterprise@2
  inputs:
    ServiceEndPointAse: 'ASE_Creds_Win37_2021'
    jobName: 'UY5'
    folderId: 12
    templateId: 7
    testPolicyId: 8
    applicationId: 1
    loginMethod: 'None'
    optimization: 'Fastest'

